name: "08ikuuu"

on:
  schedule:
    - cron: "0 14 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      #- name: Checkout master
      #  uses: actions/checkout@v2
      #  with:
      #    fetch-depth: 0
          # ref: master

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.16

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)

      - name: RUN Task
        run: |
          git clone https://github.com/hbstarjason2021/yangmao && cd yangmao/airport/
          ls -l 
          cd ikuuu
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          export IKUUU_EMAIL="${{ secrets.IKUUU_EMAIL }}"
          export IKUUU_PASSWD="${{ secrets.IKUUU_PASS }}"
          python ikuuu.py

          python3 ./main.py
          
        env:
          URL: ${{ secrets.URL }}
          SCKEY: ${{ secrets.SCKEY }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
          CONFIG: ${{ secrets.CONFIG }}
          
